#!/usr/bin/env python
'''
Created on Jun 26, 2010

@author: congnt
'''

import sys,os
import subprocess
import re
DIR='/var/cache/apt/archives/'

#Return the name of downloading file
def get_name(url):
    return url[url.rfind('/')+1:]

def download(url,part=(0,0)):
    print 'Downloading %s of %s:'%part, get_name(url)
    try:
        p = subprocess.Popen(['aria2c','--dir='+DIR,url])
        p.wait()
    
        if p.poll()==0:#if there isn't any error
            print 
            return True
    except KeyboardInterrupt:
        pass
    try:#otherwise we will remove the file
        print 'Error orcur...removing file'
        os.remove(DIR+get_name(url))
    except OSError:
        pass



print 'apt-py....'
#if we are going to download something, download it first and then run apt-get as normal
if len(sys.argv)!= 1 and sys.argv[1] in ['dist-upgrade','upgrade','install']:
    print 'Getting list of link'
    p = subprocess.Popen(['apt-get','-y', '--print-uris']+sys.argv[1:],stdout=subprocess.PIPE)
    p.wait() #wait until apt-get print all url we needed
    apt_output = p.stdout.readlines()
    url_lists = []
    for out in apt_output:
        m = re.search("(ht|f)tp://[^\']+",out)
        if m!=None:
            url_lists.append(m.group(0))
    num_url = len(url_lists)
    current = 0
    for url in url_lists:
        current +=1
        download(url,(current,num_url))
            

#after download all the file, run apt-get
try:
    p = subprocess.Popen(['apt-get']+sys.argv[1:])
    p.wait()
except KeyboardInterrupt:
    print "\nKeyboardInterrupt! Exitting"
